#!/bin/bash
set -e

# Crea las 3 bases de datos requeridas por tu diagrama
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$AUTH_DB_USER" WITH PASSWORD '$AUTH_DB_PASSWORD';
    CREATE DATABASE "$AUTH_DB_NAME" OWNER "$AUTH_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$AUTH_DB_NAME" TO "$AUTH_DB_USER";

    CREATE USER "$CHAT_DB_USER" WITH PASSWORD '$CHAT_DB_PASSWORD';
    CREATE DATABASE "$CHAT_DB_NAME" OWNER "$CHAT_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$CHAT_DB_NAME" TO "$CHAT_DB_USER";

    CREATE USER "$CATALOG_DB_USER" WITH PASSWORD '$CATALOG_DB_PASSWORD';
    CREATE DATABASE "$CATALOG_DB_NAME" OWNER "$CATALOG_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$CATALOG_DB_NAME" TO "$CATALOG_DB_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$CATALOG_DB_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS postgis;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AUTH_DB_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS postgis;
EOSQL