server {
    listen 443 ssl;
    server_name localhost;
    client_max_body_size 50m;

    ssl_certificate /etc/nginx/certs/transcendence.crt;
    ssl_certificate_key /etc/nginx/certs/transcendence.key;

    error_page 497 =301 https://$http_host$request_uri;

    # 1. Frontend
    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # 2. API CHAT -> Go to Chat Service
    location /api/chats {
        limit_req zone=api_limit burst=4000 nodelay;

        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://tr_chat:3004;

        proxy_set_header Host $host;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    }

    # 3. API REST -> Go to BFF (Backend For Frontend)
    location /api/ {
        # Aplicar rate limiting (10000 req/min + 4000 burst)
        limit_req zone=api_limit burst=4000 nodelay;

        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://bff:3000;
        proxy_set_header Host $host;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    }

    # 4. WebSockets -> Direct with Chat Service
    location /socket.io/ {
        proxy_pass http://tr_chat:3004;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
